import { initializeApollo } from '@/lib/apollo'
import { Inter } from 'next/font/google'
import ApolloProviderWrapper from './ApolloProviderWrapper'
import Banner from './Banner'
import Footer from './Footer'

import './main.css'
import PrimaryNavigation from './PrimaryNavigation'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const apolloClient = initializeApollo()

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/msx0isz.css" />
      </head>
      <body className={`${inter.variable} font-sans`}>
        <ApolloProviderWrapper client={apolloClient}>
          <Banner />
          <PrimaryNavigation />
          <main>{children}</main>
          <Footer />
        </ApolloProviderWrapper>
      </body>
    </html>
  )
}
