version: '3'
services:
  turbo:
    container_name: stitchi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: on-failure
    environment:
      PORT: 5001
  redis:
    container_name: stitchi_redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
networks:
  turbo-network:
    driver: bridge
volumes:
  redis:
    driver: local
