version: '3'
services:
  turbo:
    container_name: stitchi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./:/app/
        # Just specify a path and let the Engine create a volume
      - /app/node_modules/
    restart: on-failure
    environment:
      PORT: 5001
  redis:
    container_name: stitchi_redis
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  database:
    container_name: stitchi_database
    image: mysql:8.3.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: stitchi
      MYSQL_ROOT_PASSWORD: stitchi
    volumes:
      - mysql:/var/lib/mysql
networks:
  turbo-network:
    driver: bridge
volumes:
  redis:
    driver: local
  mysql:
    driver: local
